### ISSUE TITLE
hi - don't need write access

### ISSUE THREAD

**Issue by floswald** [JulianPasc/Final-Project-Julien-Pascal#7]
hi julien,

thanks for setting this up. note that you don't have to give me write access (I see that this is a public repository - I can see everything, as well as the entire www can see everything; if you don't like this, then you need to indeed convert this to a private repo and keep me as a collaborator with push-access). you could have just sent me the link. thats fine though - you can revoke this under settings i believe. If i have anything to contribute (unlikely), I will submit a pull request and you can incorporate that at your will.

cheers
florian

**Comment by JulienPascal** [comment]
Hi Florian,

To be fair I don't really think that it is going to interest a lot (if any)
people out there. I really don't mind keeping it public. Are there strong
reasons to make it private that I am not aware of?

Given that you can see the repository, I have "revoked" you from the list
of collaborators.

Best,
Julien

**Comment by floswald** [comment]
excellent. given that JMR's code is in the public domain already, there are 0 reasons for you not to make it public either. If you think your research is at the bleeding edge and subject to someone just copying you before you can get it published, this would be a problem; I have never heard of such a case. Obviously copying without attribution would be a blatantly illegal under any kind of license you would put the repo under. You should place your work under a license that tells people how the may reuse the code, how to cite it, etc. we could talk about that in class.

**Comment by floswald** [comment]
i won't be watching this repo now to limit email traffic. will check back by the end of term.
